I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 402, in script call
    call prologue
  File "game/script.rpy", line 43, in script
    $m(font_mozi("fonts/PixelMplus12-Regular.ttf","あははは"))
  File "game/script.rpy", line 43, in <module>
    $m(font_mozi("fonts/PixelMplus12-Regular.ttf","あははは"))
  File "game/script.rpy", line 13, in font_mozi
    return "{font={}}".format(font_name)+text+"{/font}"
ValueError: unexpected '{' in field name

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 402, in script call
    call prologue
  File "game/script.rpy", line 43, in script
    $m(font_mozi("fonts/PixelMplus12-Regular.ttf","あははは"))
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 43, in <module>
    $m(font_mozi("fonts/PixelMplus12-Regular.ttf","あははは"))
  File "game/script.rpy", line 13, in font_mozi
    return "{font={}}".format(font_name)+text+"{/font}"
ValueError: unexpected '{' in field name

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
gizin_kaden 1.0
Mon Jan 29 06:54:04 2024
