I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 86, in script call
    call prologue
  File "game/script.rpy", line 49, in script
    dot_mozi "そう思考した俺は、彼女とは別方向に倒れ込み二度寝を試みた。"
TypeError: dot_mozi() got an unexpected keyword argument 'interact'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 86, in script call
    call prologue
  File "game/script.rpy", line 49, in script
    dot_mozi "そう思考した俺は、彼女とは別方向に倒れ込み二度寝を試みた。"
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
TypeError: dot_mozi() got an unexpected keyword argument 'interact'

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
gizin_kaden 1.0
Mon Jan 29 04:58:55 2024
